apiVersion: apps/v1
kind: Deployment
metadata:
  name: merciboi-myapp
  labels:
     app: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: chydinma/myapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1


---

apiVersion: v1
kind: Service
metadata:
  name: merciboi-service
  labels:
    app: myapp 
spec:
  selector:
    app: myapp 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
